//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistSimpleCommand
    {
        public int ID { get; set; }
        public Nullable<int> Command_ID { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Material { get; set; }
        public string Source { get; set; }
        public string Target { get; set; }
        public int Task { get; set; }
        public string Segment { get; set; }
        public Nullable<int> CancelID { get; set; }
        public int Status { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Discrimator { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual HistCommand HistCommand { get; set; }
        public virtual MaterialID MaterialID { get; set; }
        public virtual PlaceID PlaceID { get; set; }
        public virtual PlaceID PlaceID1 { get; set; }
    }
}
