//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistCommand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistCommand()
        {
            this.HistSimpleCommands = new HashSet<HistSimpleCommand>();
        }
    
        public int ID { get; set; }
        public int WMS_ID { get; set; }
        public int Task { get; set; }
        public Nullable<int> Material { get; set; }
        public string Source { get; set; }
        public string Target { get; set; }
        public string Segment { get; set; }
        public Nullable<int> CommandID { get; set; }
        public int Priority { get; set; }
        public string Info { get; set; }
        public int Status { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Discrimator { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual MaterialID MaterialID { get; set; }
        public virtual PlaceID PlaceID { get; set; }
        public virtual PlaceID PlaceID1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistSimpleCommand> HistSimpleCommands { get; set; }
    }
}
